name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    name: Test before release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test

      - name: Build project
        run: bun run build

      - name: Lint check
        run: bun run check

      - name: Type check
        run: bunx tsc --noEmit

      - name: Test examples
        run: |
          echo "Testing Unspec'd framework examples..."
          timeout 5s bun run examples/lib/index.ts > /dev/null 2>&1 || true
          echo "✅ Framework examples tested"

  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Setup NPM authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish to NPM
        run: npm publish --access public

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: publish-npm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Generate release notes
        id: changelog
        run: |
          VERSION=${{ steps.version.outputs.VERSION }}
          echo "CHANGELOG=Release notes for Unspec'd Framework v$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Unspec'd Framework v${{ steps.version.outputs.VERSION }}
          body: |
            ## Unspec'd Framework v${{ steps.version.outputs.VERSION }}
            
            🚀 A new version of the Unspec'd Framework has been released!
            
            ### Features
            - Premium UI with focus mode and normal mode
            - API-based function execution
            - Enhanced CLI with exec commands
            - Improved error handling and debugging
            
            ### Installation
            ```bash
            npm install @glyphtek/unspecd
            # or
            bun add @glyphtek/unspecd
            ```
            
            ### Quick Start
            ```typescript
            import { UnspecdUI, startServer } from '@glyphtek/unspecd';
            
            const app = new UnspecdUI({ tools: [myTool] });
            await startServer(app);
            ```
            
            For more information, check out the [documentation](https://github.com/glyphtek/unspecd).
          draft: false
          prerelease: false 